package com.xyz.reservations.engine;

import com.xyz.reservations.config.Settings;
import com.xyz.reservations.service.TicketService;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ReservationApp {

    final static Log logger = LogFactory.getLog(ReservationApp.class);
    public static void main(String[] args) {

        TicketService service = TicketServiceImpl.getInstance(
                Settings.seatCount, Settings.rowCount, Settings.holdTimeout);

        ConsoleHandler.readConsole(service);
    }
}
