/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.xyz.reservations.engine.ReservationApp;
import org.junit.Test;

public class ReservationAppTest {
    @Test public void testAppHasAGreeting() {
        ReservationApp classUnderTest = new ReservationApp();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
